### ISSUE TITLE
path of zoom in linux

### ISSUE THREAD

**Issue by sivasaran1** [DeeshanSharma/Zoom-Bot#1]
help me to find the path of zoom in linux executable

**Comment by DeeshanSharma** [comment]
Actually, it depends on how you install it, probably it could be in your downloads folder. I would suggest you follow the official installation documentation from zoom. ref: https://support.zoom.us/hc/en-us/articles/204206269-Installing-or-updating-Zoom-on-Linux

**Comment by SerxoLaxe** [comment]
> help me to find the path of zoom in linux executable

/usr/bin/zoom does the trick for me.
